=== Venkat96r/Content_blender/cbank_schema_simple.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           targetNamespace="http://contentrepurpose.com/cbank"
           xmlns:cb="http://contentrepurpose.com/cbank"
           elementFormDefault="qualified">


    <xs:element name="CBank">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ContentBlock" type="cb:ContentBlockType" 
                            minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="ContentBlockType">
        <xs:sequence>
            <xs:element name="Title" type="xs:string"/>
            <xs:element name="Author" type="xs:string"/>
            <xs:element name="CreatedDate" type="xs:date"/>
            <xs:element name="Tags" type="cb:TagsType" minOccurs="0"/>
            <xs:element name="Content" type="cb:ContentType"/>
        </xs:sequence>
        
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="type" type="cb:ContentTypeEnum" use="required"/>
    </xs:complexType>

    <xs:complexType name="TagsType">
        <xs:sequence>
            <xs:element name="Tag" type="xs:string" 
                        minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ContentType">
        <xs:choice>
            <xs:element name="Text" type="xs:string"/>
            
            <xs:element name="Image">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="URL" type="xs:anyURI"/>
                        <xs:element name="AltText" type="xs:string" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="Data" type="xs:string"/>
        </xs:choice>
    </xs:complexType>

    <xs:simpleType name="ContentTypeEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="text"/>
            <xs:enumeration value="image"/>
            <xs:enumeration value="data"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Venkat96r/Content_blender/cbank_example_simple.xml
<?xml version="1.0" encoding="UTF-8"?>
<CBank xmlns="http://contentrepurpose.com/cbank"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://contentrepurpose.com/cbank cbank_schema_simple.xsd"
       id="CBANK001"
       name="My Content Library">
 
    <ContentBlock id="CB001" type="text">
        <Title>Welcome Message</Title>
        <Author>John Smith</Author>
        <CreatedDate>2026-02-15</CreatedDate>
        <Tags>
            <Tag>introduction</Tag>
            <Tag>welcome</Tag>
        </Tags>
        <Content>
            <Text>Welcome to our platform! We're excited to have you here. 
            This guide will help you get started with all the amazing features 
            we offer. Let's dive in!</Text>
        </Content>
    </ContentBlock>

    <ContentBlock id="CB002" type="image">
        <Title>Product Dashboard</Title>
        <Author>Design Team</Author>
        <CreatedDate>2026-02-14</CreatedDate>
        <Tags>
            <Tag>screenshot</Tag>
            <Tag>dashboard</Tag>
        </Tags>
        <Content>
            <Image>
                <URL>https://example.com/images/dashboard.png</URL>
                <AltText>Dashboard showing analytics and metrics</AltText>
            </Image>
        </Content>
    </ContentBlock>

    <ContentBlock id="CB003" type="data">
        <Title>Key Statistics</Title>
        <Author>Analytics Team</Author>
        <CreatedDate>2026-02-13</CreatedDate>
        <Tags>
            <Tag>statistics</Tag>
            <Tag>metrics</Tag>
        </Tags>
        <Content>
            <Data>
                {
                    "users": "10,000+",
                    "satisfaction": "98%",
                    "countries": "50+"
                }
            </Data>
        </Content>
    </ContentBlock>

    <ContentBlock id="CB004" type="text">
        <Title>Customer Testimonial</Title>
        <Author>Customer Success Team</Author>
        <CreatedDate>2026-02-12</CreatedDate>
        <Tags>
            <Tag>testimonial</Tag>
            <Tag>customer</Tag>
        </Tags>
        <Content>
            <Text>"This platform has transformed how we work. Highly recommended!"
            - Sarah Johnson, CEO of TechCorp</Text>
        </Content>
    </ContentBlock>

</CBank>
