=== Venkat96r/Content_blender/cblend_schema_simple.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           targetNamespace="http://contentrepurpose.com/cblend"
           xmlns:cbl="http://contentrepurpose.com/cblend"
           elementFormDefault="qualified">


    <xs:element name="CBlend">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" type="xs:string"/>
                <xs:element name="Purpose" type="xs:string" minOccurs="0"/>
                <xs:element name="CreatedBy" type="xs:string"/>
                <xs:element name="CreatedDate" type="xs:date"/>                
                <xs:element name="TargetPlatform" type="cbl:PlatformType" minOccurs="0"/>                
                <xs:element name="SelectedBlocks" type="cbl:SelectedBlocksType"/>                
                <xs:element name="Modifications" type="cbl:ModificationsType" minOccurs="0"/>
            </xs:sequence>
            
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="status" type="cbl:StatusType" default="draft"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="PlatformType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="blog"/>
            <xs:enumeration value="social-media"/>
            <xs:enumeration value="email"/>
            <xs:enumeration value="presentation"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="StatusType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="draft"/>
            <xs:enumeration value="in-progress"/>
            <xs:enumeration value="completed"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="SelectedBlocksType">
        <xs:sequence>
            <xs:element name="BlockReference" type="cbl:BlockReferenceType" 
                        minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="BlockReferenceType">
        <xs:sequence>
            <xs:element name="Position" type="xs:positiveInteger"/>
            <xs:element name="Notes" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="blockId" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="ModificationsType">
        <xs:sequence>
            <xs:element name="Modification" type="cbl:ModificationType" 
                        minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ModificationType">
        <xs:sequence>
            <xs:element name="Type" type="cbl:ModificationTypeEnum"/>
            <xs:element name="Description" type="xs:string" minOccurs="0"/>
            <xs:element name="AppliedDate" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:simpleType name="ModificationTypeEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="tone-change"/>
            <xs:enumeration value="expand"/>
            <xs:enumeration value="summarize"/>
            <xs:enumeration value="translate"/>
            <xs:enumeration value="reformat"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Venkat96r/Content_blender/cblend_example_simple.xml
<?xml version="1.0" encoding="UTF-8"?>
<CBlend xmlns="http://contentrepurpose.com/cblend"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://contentrepurpose.com/cblend cblend_schema_simple.xsd"
        id="BL001"
        status="completed">

    <Name>Welcome Blog Post</Name>
    <Purpose>Create a blog post introducing our platform to new users</Purpose>
    <CreatedBy>Marketing Team</CreatedBy>
    <CreatedDate>2026-02-15</CreatedDate>
    <TargetPlatform>blog</TargetPlatform>

    <SelectedBlocks>
        
        <BlockReference blockId="CB001">
            <Position>1</Position>
            <Notes>Use as introduction</Notes>
        </BlockReference>
        
        <BlockReference blockId="CB002">
            <Position>2</Position>
            <Notes>Visual break in the middle</Notes>
        </BlockReference>
        
        <BlockReference blockId="CB003">
            <Position>3</Position>
            <Notes>Show impressive numbers</Notes>
        </BlockReference>
        
        <BlockReference blockId="CB004">
            <Position>4</Position>
            <Notes>End with social proof</Notes>
        </BlockReference>
        
    </SelectedBlocks>

    <Modifications>
        
        <Modification id="MOD001">
            <Type>tone-change</Type>
            <Description>Changed tone to be more professional for blog audience</Description>
            <AppliedDate>2026-02-15</AppliedDate>
        </Modification>
        
        <Modification id="MOD002">
            <Type>expand</Type>
            <Description>Added more details to welcome message</Description>
            <AppliedDate>2026-02-15</AppliedDate>
        </Modification>
        
    </Modifications>

</CBlend>
